package com.mod.mapper;

import java.util.HashMap;
import java.util.LinkedList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.mod.bean.OrderForm;
@MapperScan
public interface OrderFormMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderform
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	int insert(OrderForm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderform
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	int insertSelective(OrderForm record);
	int updateByPrimaryKeyChangePk(@Param("n")OrderForm n,@Param("old")OrderForm old);
	LinkedList<HashMap<String, Object>> getOrderList(@Param("oid") Long oid, @Param("uid") Integer uid);

	LinkedList<HashMap<String, Object>> getOrderList(@Param("oid") String oid, @Param("uid") Integer uid);

	@Delete(" delete from orderform where oid = #{oid,jdbcType=DECIMAL} and uid = #{uid,jdbcType=INTEGER}")
	int deleByOUid(@Param("oid") Long oid, @Param("uid") Integer uid);
}