package com.mod.mapper;

import java.util.ArrayList;
import java.util.HashMap;

import org.mybatis.spring.annotation.MapperScan;

import com.mod.bean.Region;
import com.mod.bean.RegionInfo;
@MapperScan
public interface RegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    int insert(Region record);
    ArrayList<RegionInfo> getRegionInfo();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    int insertSelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    Region selectByPrimaryKey(Integer id);

    ArrayList<Region> selectByLevel(Integer level);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    int updateByPrimaryKeySelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    int updateByPrimaryKey(Region record);
}