package com.mod.mapper;

import java.util.HashMap;
import java.util.LinkedList;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.mod.bean.ShoppingCar;
@MapperScan
public interface ShoppingCarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shoppingcar
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	int deleteByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shoppingcar
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	int insert(ShoppingCar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shoppingcar
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	int insertSelective(ShoppingCar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shoppingcar
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	ShoppingCar selectByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shoppingcar
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	int updateByPrimaryKeySelective(ShoppingCar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shoppingcar
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	int updateByPrimaryKey(ShoppingCar record);
	int updateByPrimaryKeyChangePk(@Param("s")ShoppingCar s,@Param("pk")int pk);
	LinkedList<ShoppingCar> getCarListByUid(@Param("uid") Integer uid);

	LinkedList<HashMap<String, Object>> getCarView(@Param("uid") Integer uid);

	ShoppingCar selectByUGid(@Param("uid") Integer uid, @Param("gid") Integer gid);

	int queryCarNum(@Param("uid") Integer uid);
}