package com.mod.bean;

import org.springframework.stereotype.Component;

@Component("goodsAndroid")
public class GoodsAndroid {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodsand.goodsId
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private Integer goodsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodsand.text
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private String text;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodsand.imageUrl
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private String imageurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodsand.spanSize
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private Integer spansize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodsand.banners
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private String banners;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodsand.descption
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private String descption;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodsand.goodsId
	 * @return  the value of goodsand.goodsId
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public Integer getGoodsid() {
		return goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodsand.goodsId
	 * @param goodsid  the value for goodsand.goodsId
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodsand.text
	 * @return  the value of goodsand.text
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodsand.text
	 * @param text  the value for goodsand.text
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodsand.imageUrl
	 * @return  the value of goodsand.imageUrl
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public String getImageurl() {
		return imageurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodsand.imageUrl
	 * @param imageurl  the value for goodsand.imageUrl
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodsand.spanSize
	 * @return  the value of goodsand.spanSize
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public Integer getSpansize() {
		return spansize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodsand.spanSize
	 * @param spansize  the value for goodsand.spanSize
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setSpansize(Integer spansize) {
		this.spansize = spansize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodsand.banners
	 * @return  the value of goodsand.banners
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public String getBanners() {
		return banners;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodsand.banners
	 * @param banners  the value for goodsand.banners
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setBanners(String banners) {
		this.banners = banners;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodsand.descption
	 * @return  the value of goodsand.descption
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public String getDescption() {
		return descption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodsand.descption
	 * @param descption  the value for goodsand.descption
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setDescption(String descption) {
		this.descption = descption;
	}
}