package com.mod.bean;

import org.springframework.stereotype.Component;

@Component("qrcheck")
public class Qrcheck {
	
	
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.uuid
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.status
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.name
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.pwd
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	private String pwd;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.uuid
	 * @return  the value of qrcheck.uuid
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.uuid
	 * @param uuid  the value for qrcheck.uuid
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.status
	 * @return  the value of qrcheck.status
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.status
	 * @param status  the value for qrcheck.status
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.name
	 * @return  the value of qrcheck.name
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.name
	 * @param name  the value for qrcheck.name
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.pwd
	 * @return  the value of qrcheck.pwd
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.pwd
	 * @param pwd  the value for qrcheck.pwd
	 * @mbggenerated  Mon Nov 27 11:55:23 CST 2017
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Qrcheck() {
		super();
	}

	public Qrcheck(String uuid, Integer status) {
		super();
		this.uuid = uuid;
		this.status = status;
	}

	
	public Qrcheck(String uuid, Integer status, String name, String pwd) {
		super();
		this.uuid = uuid;
		this.status = status;
		this.name = name;
		this.pwd = pwd;
	}
}