package com.mod.bean;

import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.annotation.JdbcType;
import com.annotation.JdbcType.TYPE;

@Component
@JsonIgnoreProperties(ignoreUnknown = true)
public class Qrcheck {
	
	
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.uuid
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	@JdbcType(type = TYPE.varchar, required = true)
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.status
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	@JdbcType(type = TYPE.intonly, required = true, max = 2, maxLen = 1, min = 0, minLen = 1)
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.name
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	@JdbcType(type = TYPE.varchar, required = false)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qrcheck.pwd
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	@JdbcType(type = TYPE.varchar, required = false)
	private String pwd;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.uuid
	 * @return  the value of qrcheck.uuid
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.uuid
	 * @param uuid  the value for qrcheck.uuid
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.status
	 * @return  the value of qrcheck.status
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.status
	 * @param status  the value for qrcheck.status
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.name
	 * @return  the value of qrcheck.name
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.name
	 * @param name  the value for qrcheck.name
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qrcheck.pwd
	 * @return  the value of qrcheck.pwd
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qrcheck.pwd
	 * @param pwd  the value for qrcheck.pwd
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Qrcheck() {
		super();
	}

	public Qrcheck(String uuid, Integer status) {
		super();
		this.uuid = uuid;
		this.status = status;
	}

	
	public Qrcheck(String uuid, Integer status, String name, String pwd) {
		super();
		this.uuid = uuid;
		this.status = status;
		this.name = name;
		this.pwd = pwd;
	}
}