package com.mod.bean;

import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@Component
@JsonIgnoreProperties(ignoreUnknown = true)
public class Region {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.id
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.pid
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.shortname
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.name
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.merger_name
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String mergerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.level
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.pinyin
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.code
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.zip_code
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.first
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String first;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.lng
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.lat
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    private String lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.id
     *
     * @return the value of region.id
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.id
     *
     * @param id the value for region.id
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.pid
     *
     * @return the value of region.pid
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.pid
     *
     * @param pid the value for region.pid
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.shortname
     *
     * @return the value of region.shortname
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.shortname
     *
     * @param shortname the value for region.shortname
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.name
     *
     * @return the value of region.name
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.name
     *
     * @param name the value for region.name
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.merger_name
     *
     * @return the value of region.merger_name
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.merger_name
     *
     * @param mergerName the value for region.merger_name
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.level
     *
     * @return the value of region.level
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.level
     *
     * @param level the value for region.level
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.pinyin
     *
     * @return the value of region.pinyin
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.pinyin
     *
     * @param pinyin the value for region.pinyin
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.code
     *
     * @return the value of region.code
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.code
     *
     * @param code the value for region.code
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.zip_code
     *
     * @return the value of region.zip_code
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.zip_code
     *
     * @param zipCode the value for region.zip_code
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.first
     *
     * @return the value of region.first
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getFirst() {
        return first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.first
     *
     * @param first the value for region.first
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setFirst(String first) {
        this.first = first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.lng
     *
     * @return the value of region.lng
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.lng
     *
     * @param lng the value for region.lng
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setLng(String lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.lat
     *
     * @return the value of region.lat
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.lat
     *
     * @param lat the value for region.lat
     *
     * @mbggenerated Tue Dec 05 14:45:23 CST 2017
     */
    public void setLat(String lat) {
        this.lat = lat;
    }
}